version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 19
  pre_build:
    commands:
      - cd alucar-api    
  build:
    commands:
      -mvn clean package

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
